package Vista.Panel.Menu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Vista.Paneles.Contenido.Cont_Clientes;
import Vista.Paneles.Contenido.Cont_Finanzas;
import Vista.Paneles.Contenido.Cont_Productos;
import Vista.Paneles.Contenido.Cont_Habitaciones;
import Vista.Paneles.Contenido.Panel_Bienvenida;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/*
 * @author Cochy
 */

public class Menu_Adminstrador extends javax.swing.JPanel {
    /**
     * Creates new form Menu_Empleado
     */
    public Menu_Adminstrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinancieros = new javax.swing.JButton();
        btnHabitaciones = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(12, 8, 53));
        setMinimumSize(new java.awt.Dimension(191, 300));
        setPreferredSize(new java.awt.Dimension(191, 300));

        btnFinancieros.setText("FINANCIEROS");
        btnFinancieros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancierosActionPerformed(evt);
            }
        });

        btnHabitaciones.setText("HABITACIONES");
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });

        btnProductos.setText("PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnClientes.setText("CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GRAFICOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinancieros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinancieros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHabitaciones)
                .addGap(18, 18, 18)
                .addComponent(btnProductos)
                .addGap(18, 18, 18)
                .addComponent(btnClientes)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        if (pCliente.isVisible()) {
            pCliente.setVisible(false);
            pBienve.setVisible(true);
        }else{
            pCliente.setVisible(true);
            pBienve.setVisible(false);
        }        
        pHabita.setVisible(false);
        pFinan.setVisible(false);
        pProduc.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        if (pProduc.isVisible()) {
            pProduc.setVisible(false);
            pBienve.setVisible(true);
        }else{
            pProduc.setVisible(true);
            pBienve.setVisible(false);
        }
        pCliente.setVisible(false);
        pHabita.setVisible(false);
        pFinan.setVisible(false);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        // TODO add your handling code here:
        if (pHabita.isVisible()) {
            pHabita.setVisible(false);
            pBienve.setVisible(true);
        }else{
            pHabita.setVisible(true);
            pBienve.setVisible(false);
        }
        pCliente.setVisible(false);
        pFinan.setVisible(false);
        pProduc.setVisible(false);
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnFinancierosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancierosActionPerformed
        // TODO add your handling code here:
        if (pFinan.isVisible()) {
            pFinan.setVisible(false);
            pBienve.setVisible(true);
        }else{
            pFinan.setVisible(true);
            pBienve.setVisible(false);
        }
        pCliente.setVisible(false);
        pHabita.setVisible(false);
        pProduc.setVisible(false);
    }//GEN-LAST:event_btnFinancierosActionPerformed
    GridBagLayout layout = new GridBagLayout();
    JPanel cuerpo;
    Cont_Habitaciones pHabita;
    Cont_Finanzas pFinan;
    Cont_Productos pProduc;
    Cont_Clientes pCliente;
    Panel_Bienvenida pBienve;
    public void instanciarPaneles(JPanel pCuerpo){
        pHabita = new Cont_Habitaciones();
        pFinan = new Cont_Finanzas();
        pProduc = new Cont_Productos();
        pBienve = new Panel_Bienvenida();
        pCliente = new Cont_Clientes();
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        pCuerpo.setLayout(new BoxLayout(pCuerpo,BoxLayout.PAGE_AXIS));
        pCuerpo.add(pHabita,c);
        pCuerpo.add(pFinan,c);
        pCuerpo.add(pProduc,c);
        pCuerpo.add(pBienve,c);
        pCuerpo.add(pCliente,c);
        pHabita.setVisible(false);
        pFinan.setVisible(false);
        pProduc.setVisible(false);
        pBienve.setVisible(true);
        pCliente.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFinancieros;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
