/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles.Contenido;

import Controlador.PanelHabitaciones;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Cochy
 */
public class Cont_Habitaciones extends javax.swing.JPanel {

    /**
     * Creates new form Cont_Empleado
     */
    
    private PanelHabitaciones _pHabitaciones;
    
    public Cont_Habitaciones() {
        initComponents();
        _pHabitaciones = new PanelHabitaciones();
        pHabitacionesCuerpo.setVisible(true);
        pSolicitudesCuerpo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pHabitaciones = new javax.swing.JPanel();
        pHabitacionesCuerpo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarEstadoHabit = new javax.swing.JButton();
        btnGenerarHabitSolic = new javax.swing.JButton();
        pSolicitudes = new javax.swing.JPanel();
        pSolicitudesCuerpo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGenerarFechaMayor = new javax.swing.JButton();
        btnGenerarCantSolicit = new javax.swing.JButton();

        setBackground(new java.awt.Color(12, 8, 53));
        setMinimumSize(new java.awt.Dimension(690, 550));
        setPreferredSize(new java.awt.Dimension(690, 550));

        jTabbedPane1.setBackground(new java.awt.Color(12, 8, 53));

        pHabitaciones.setBackground(new java.awt.Color(37, 36, 39));

        pHabitacionesCuerpo.setBackground(new java.awt.Color(37, 36, 39));
        pHabitacionesCuerpo.setMinimumSize(new java.awt.Dimension(0, 420));
        pHabitacionesCuerpo.setPreferredSize(new java.awt.Dimension(0, 420));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado de las Habitaciones");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Habitaciones Mas Solicitadas");

        btnGenerarEstadoHabit.setText("GENERAR");
        btnGenerarEstadoHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarEstadoHabitActionPerformed(evt);
            }
        });

        btnGenerarHabitSolic.setText("GENERAR");
        btnGenerarHabitSolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarHabitSolicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pHabitacionesLayout = new javax.swing.GroupLayout(pHabitaciones);
        pHabitaciones.setLayout(pHabitacionesLayout);
        pHabitacionesLayout.setHorizontalGroup(
            pHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pHabitacionesCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pHabitacionesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarEstadoHabit))
                    .addGroup(pHabitacionesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarHabitSolic)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        pHabitacionesLayout.setVerticalGroup(
            pHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnGenerarEstadoHabit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnGenerarHabitSolic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(pHabitacionesCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Habitaciones", pHabitaciones);

        pSolicitudes.setBackground(new java.awt.Color(37, 36, 39));

        pSolicitudesCuerpo.setBackground(new java.awt.Color(37, 36, 39));
        pSolicitudesCuerpo.setMinimumSize(new java.awt.Dimension(0, 420));
        pSolicitudesCuerpo.setPreferredSize(new java.awt.Dimension(0, 420));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Mayor Auge");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de Solicitudes no Finalizadas");

        btnGenerarFechaMayor.setText("GENERAR");
        btnGenerarFechaMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFechaMayorActionPerformed(evt);
            }
        });

        btnGenerarCantSolicit.setText("GENERAR");
        btnGenerarCantSolicit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCantSolicitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSolicitudesLayout = new javax.swing.GroupLayout(pSolicitudes);
        pSolicitudes.setLayout(pSolicitudesLayout);
        pSolicitudesLayout.setHorizontalGroup(
            pSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pSolicitudesCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pSolicitudesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarFechaMayor)
                    .addComponent(btnGenerarCantSolicit))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        pSolicitudesLayout.setVerticalGroup(
            pSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSolicitudesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnGenerarFechaMayor))
                .addGap(10, 10, 10)
                .addGroup(pSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnGenerarCantSolicit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(pSolicitudesCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Solicitudes", pSolicitudes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarEstadoHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarEstadoHabitActionPerformed
        // TODO add your handling code here:
        _pHabitaciones.Estado_habitaciones();
        /*
        DefaultCategoryDataset dt = new DefaultCategoryDataset();
        List<?> lista = _habitacionesControlador.estadoHabitaciones();
        if(lista==null){
            JOptionPane.showMessageDialog(this,"No hay datos");
        }else{
            String[] estado= new String[3];
            int[] cantidad = new int[3];
            for (int i = 0; i < lista.size(); i++) {
                Object[] row = (Object[]) lista.get(i);
                estado[i] = row[0].toString();
                cantidad[i]=Integer.parseInt(row[1].toString());
            }
            dt.setValue(cantidad[0],estado[0],"Mantenimiento".toUpperCase());
            dt.setValue(cantidad[1],estado[1],estado[1].toUpperCase());
            dt.setValue(cantidad[2],estado[2],estado[2].toUpperCase());
            
            JFreeChart jf = ChartFactory.createBarChart("Estado de las Habitaciones", "Categorias","Cantidad",dt,PlotOrientation.VERTICAL,true,true,false);
            jf.setBackgroundPaint(Color.white);
            
            ChartPanel cp = new ChartPanel(jf);
            /*
            chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
            chartPanel.setVisible(true);
            
            pHabitacionesCuerpo.setVisible(true);
            cp.setPreferredSize(new java.awt.Dimension(500, 270));
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 100;
            c.gridy = 100;
            pHabitacionesCuerpo.add(cp ,c);
        }
        */
    }//GEN-LAST:event_btnGenerarEstadoHabitActionPerformed

    private void btnGenerarHabitSolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarHabitSolicActionPerformed
        // TODO add your handling code here:
        _pHabitaciones.Habitaciones_mas_solicitadas();
    }//GEN-LAST:event_btnGenerarHabitSolicActionPerformed

    private void btnGenerarFechaMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFechaMayorActionPerformed
        // TODO add your handling code here:
        _pHabitaciones.Fecha_mayor_auge();
    }//GEN-LAST:event_btnGenerarFechaMayorActionPerformed

    private void btnGenerarCantSolicitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCantSolicitActionPerformed
        // TODO add your handling code here:
        _pHabitaciones.Solicitudes_NO_terminadas();
    }//GEN-LAST:event_btnGenerarCantSolicitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarCantSolicit;
    private javax.swing.JButton btnGenerarEstadoHabit;
    private javax.swing.JButton btnGenerarFechaMayor;
    private javax.swing.JButton btnGenerarHabitSolic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pHabitaciones;
    private javax.swing.JPanel pHabitacionesCuerpo;
    private javax.swing.JPanel pSolicitudes;
    private javax.swing.JPanel pSolicitudesCuerpo;
    // End of variables declaration//GEN-END:variables
}
