/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles.Contenido;

import Controlador.PanelProductos;

/**
 *
 * @author Cochy
 */
public class Cont_Productos extends javax.swing.JPanel {

    /**
     * Creates new form Cont_Emp_Productos
     */
    
    private PanelProductos _pProductos;
    
    public Cont_Productos() {
        initComponents();
        _pProductos = new PanelProductos();
        pProductoCuerpo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pProducto = new javax.swing.JPanel();
        pProductoCuerpo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProdStock = new javax.swing.JButton();
        btnProdMasSolic = new javax.swing.JButton();

        setBackground(new java.awt.Color(12, 8, 53));
        setMinimumSize(new java.awt.Dimension(690, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(690, 550));

        jTabbedPane1.setBackground(new java.awt.Color(12, 8, 53));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(670, 530));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(670, 530));

        pProducto.setBackground(new java.awt.Color(37, 36, 39));

        pProductoCuerpo.setBackground(new java.awt.Color(37, 36, 39));
        pProductoCuerpo.setMinimumSize(new java.awt.Dimension(0, 420));
        pProductoCuerpo.setPreferredSize(new java.awt.Dimension(0, 420));

        javax.swing.GroupLayout pProductoCuerpoLayout = new javax.swing.GroupLayout(pProductoCuerpo);
        pProductoCuerpo.setLayout(pProductoCuerpoLayout);
        pProductoCuerpoLayout.setHorizontalGroup(
            pProductoCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pProductoCuerpoLayout.setVerticalGroup(
            pProductoCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos en Stock");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos Mas Solicitados");

        btnProdStock.setText("GENERAR");
        btnProdStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdStockActionPerformed(evt);
            }
        });

        btnProdMasSolic.setText("GENERAR");
        btnProdMasSolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdMasSolicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pProductoLayout = new javax.swing.GroupLayout(pProducto);
        pProducto.setLayout(pProductoLayout);
        pProductoLayout.setHorizontalGroup(
            pProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pProductoCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
            .addGroup(pProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pProductoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(btnProdStock))
                    .addGroup(pProductoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProdMasSolic)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        pProductoLayout.setVerticalGroup(
            pProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnProdStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnProdMasSolic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(pProductoCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Producto", pProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdStockActionPerformed
        // TODO add your handling code here:
        _pProductos.StockProductos();
    }//GEN-LAST:event_btnProdStockActionPerformed

    private void btnProdMasSolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdMasSolicActionPerformed
        // TODO add your handling code here:
        _pProductos.Productos_mas_solicitados();
    }//GEN-LAST:event_btnProdMasSolicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdMasSolic;
    private javax.swing.JButton btnProdStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pProducto;
    private javax.swing.JPanel pProductoCuerpo;
    // End of variables declaration//GEN-END:variables
}
