/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles.Contenido;

import Controlador.PanelFinanzas;

/**
 *
 * @author Cochy
 */
public class Cont_Finanzas extends javax.swing.JPanel {

    /**
     * Creates new form Cont_Emp_Productos
     */
    
    private PanelFinanzas _pFinanzas;
    
    public Cont_Finanzas() {
        initComponents();
        _pFinanzas = new PanelFinanzas();
        pVentasCuerpo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pVentas = new javax.swing.JPanel();
        pVentasCuerpo = new javax.swing.JPanel();
        btnPromVentMens = new javax.swing.JButton();
        btnPromedPerdMens = new javax.swing.JButton();
        btnPorcenCierreEfect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(12, 8, 53));
        setMinimumSize(new java.awt.Dimension(690, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(690, 550));

        jTabbedPane1.setBackground(new java.awt.Color(12, 8, 53));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(670, 530));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(670, 530));

        pVentas.setBackground(new java.awt.Color(37, 36, 39));

        pVentasCuerpo.setBackground(new java.awt.Color(37, 36, 39));
        pVentasCuerpo.setMinimumSize(new java.awt.Dimension(0, 420));
        pVentasCuerpo.setPreferredSize(new java.awt.Dimension(0, 420));

        javax.swing.GroupLayout pVentasCuerpoLayout = new javax.swing.GroupLayout(pVentasCuerpo);
        pVentasCuerpo.setLayout(pVentasCuerpoLayout);
        pVentasCuerpoLayout.setHorizontalGroup(
            pVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        pVentasCuerpoLayout.setVerticalGroup(
            pVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        btnPromVentMens.setText("GENERAR");
        btnPromVentMens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromVentMensActionPerformed(evt);
            }
        });

        btnPromedPerdMens.setText("GENERAR");
        btnPromedPerdMens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedPerdMensActionPerformed(evt);
            }
        });

        btnPorcenCierreEfect.setText("GENERAR");
        btnPorcenCierreEfect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcenCierreEfectActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Promedio de Ventas Mensuales");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Promedio de Perdida Mensual");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Porcentaje de Cierre Efectivo");

        javax.swing.GroupLayout pVentasLayout = new javax.swing.GroupLayout(pVentas);
        pVentas.setLayout(pVentasLayout);
        pVentasLayout.setHorizontalGroup(
            pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pVentasCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
            .addGroup(pVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPorcenCierreEfect)
                    .addComponent(btnPromedPerdMens)
                    .addComponent(btnPromVentMens))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pVentasLayout.setVerticalGroup(
            pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromVentMens)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromedPerdMens)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPorcenCierreEfect)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pVentasCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Ventas", pVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromVentMensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromVentMensActionPerformed
        // TODO add your handling code here:
        _pFinanzas.Promedio_venta_mensual();
    }//GEN-LAST:event_btnPromVentMensActionPerformed

    private void btnPromedPerdMensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedPerdMensActionPerformed
        // TODO add your handling code here:
        _pFinanzas.Promedio_perdida_mensual();
    }//GEN-LAST:event_btnPromedPerdMensActionPerformed

    private void btnPorcenCierreEfectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcenCierreEfectActionPerformed
        // TODO add your handling code here:
        _pFinanzas.Porcentage_cierre_efectivo();
    }//GEN-LAST:event_btnPorcenCierreEfectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPorcenCierreEfect;
    private javax.swing.JButton btnPromVentMens;
    private javax.swing.JButton btnPromedPerdMens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pVentas;
    private javax.swing.JPanel pVentasCuerpo;
    // End of variables declaration//GEN-END:variables
}
